### ISSUE TITLE
JS error / error calling function loadbang

### ISSUE THREAD

**Issue by tomduncalf** [playbenny/benny#442]
Hey! 

First of all huge thanks for releasing this open source. So cool and exciting, can't wait to play with it!

I'm unable to start Benny on my M1 Macbook, I see no "start" button and I see two errors in the Max console:

<img width="687" alt="image" src="https://github.com/user-attachments/assets/ce2046db-c986-407d-b32b-502ef33858b5">

Which appears to be this line: https://github.com/playbenny/benny/blob/main/code/files.js#L111

I wondered if you had any idea what might be wrong? I'm on Max 8.6.2.

Cheers,
Tom

**Comment by tomduncalf** [comment]
Oh, I also see these errors at the top about a few object it could not find - would this break the startup?

<img width="687" alt="image" src="https://github.com/user-attachments/assets/e00a0a15-184e-4de1-a9e7-e0ce00e07b91">

**Comment by jamesholdenmusic** [comment]
hi tom, thanks for this. i can recreate it here (by deleting my own userconfig.json which triggers it's first run defaults setup). i think i've introduced a bug - that function is quite recent. brb asap!

**Comment by tomduncalf** [comment]
Awesome, thanks!

**Comment by jamesholdenmusic** [comment]
think i got it? the new section had only been tested on an existing install with a songs folder full of songs.
feel free to reopen if i havent. thanks again!

**Comment by tomduncalf** [comment]
Thanks! I’ll test it out tomorrow and let you know :)

**Comment by tomduncalf** [comment]
This fixed it, thanks! Really amazing work on this project, wow :)
